model_list:
  - model_name: gemini-flash
    litellm_params:
      model: vertex_ai/gemini-2.5-flash
      vertex_project: robotshop-platform-dev
      vertex_location: asia-south1

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  custom_auth: custom_auth.user_api_key_auth
  custom_auth_settings:
    mode: "auto"